---
# The ndtech-staging Pipeline will run through several tasks:
# - source is pulled from git
# - source is built into an image
# - image output is pushed to dockerhub
# - cloudevent emitted
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: ndtech-staging-pipeline
  namespace: ndtech-staging
spec:
  resources:
    - name: source-repo
      type: git
    - name: image-source
      type: image
    - name: event-to-sink
      type: cloudEvent
  tasks:
    - name: build-docker-image
      taskRef:
        name: build-docker-image
      params:
        - name: pathToContext
          value: /workspace/source-repo
      resources:
        inputs:
          - name: source-repo
            resource: source-repo
        outputs:
          - name: builtImage
            resource: image-source
    - name: deploy-to-ndtech-staging
      taskRef:
        name: deploy-to-ndtech-staging
      resources:
        inputs:
          - name: image-source
            resource: image-source
            from:
              - build-docker-image