---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-docker-image
  namespace: ndtech-staging
spec:
  params:
  - name: pathToContext
    description: |
        The build context used by Kaniko
        (https://github.com/GoogleContainerTools/kaniko#kaniko-build-contexts)
    default: .
  - name: pathToDockerFile
    type: string
    description: The path to the dockerfile to build
    default: ./Dockerfile
  - name: app-version
    type: string
    description: The version of the app to build also used as the image version
  workspaces:
    - name: app-source
  results:
    - name: built-image-url
      description: url of the image built
  steps:

    - name: build-and-push
      image: gcr.io/kaniko-project/executor:v1.5.0
      workingDir: "$(workspaces.app-source.path)"
      command:
        - /kaniko/executor
      args:
        - --dockerfile=$(params.pathToDockerFile)
        - --destination="22ndtech/ndtech-website:0.0.5"
        - --context=$(params.pathToContext)