---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: clone
  namespace: ndtech-staging
spec:
  params:
  - name: gitHubOrg
  - name: gitHubRepo
  - name: buildRevision
  workspaces:
    - name: app-source
  steps:

  - name: clone
    image: alpine/git:v2.26.2
    workingDir: "$(workspaces.app-source.path)"
    script: |
      git init
      git remote add origin https://github.com/$(inputs.params.gitHubOrg)/$(inputs.params.gitHubRepo).git
      git fetch --depth 1 origin master
      git checkout master

      echo ""
      pwd
      ls -la ./
      date
