---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy-to-ndtech-staging
  namespace: ndtech-staging
spec:
  params:
  - name: buildRevision
  - name: app-name
  - name: app-version
  workspaces:
    - name: config-source
  stepTemplate:
    name: stepTemplate
    envFrom:
    - secretRef:
        name: 22ndtech-admin-github-token
  results:
    - name: imageVersion
      description: version of the image
  steps:

  - name: checkout-main
    image: alpine/git:v2.26.2
    workingDir: "$(workspaces.config-source.path)"
    script: |
      #!/usr/bin/env sh
      set -e
      git checkout main

  - name: update-yaml
    image: mikefarah/yq:4
    workingDir: "$(workspaces.config-source.path)"
    script: |
      #!/usr/bin/env sh
      set -e
      yq e '.spec.values.deployment.imageVersion = "$(inputs.params.app-version)"' -i ./apps/$(inputs.params.app-name)/$(inputs.params.app-name)-helmrelease.yaml

  - name: commit-updates
    image: alpine/git:v2.26.2
    workingDir: "$(workspaces.config-source.path)"
    script: |
      #!/usr/bin/env sh
      set -e
      git config --global user.email "admin@22ndtech.com"
      git config --global user.name "22ndtech Admin"
      git add .

      echo "********** token ***********"
      echo $token
      echo "********** app-version ***********"

      git remote set-url origin https://22ndtech-admin:${token}@github.com/22ndtech/ndtech-flux-staging.git

      git remote -v

      echo "commit changes"
      git commit --allow-empty -m "[ndtech-staging:tekton] updating ndtech-staging image to app-version:$(inputs.params.app-version) and buildRevision:$(inputs.params.buildRevision)"
      git push origin main
      
  - name: wait-for-flux-reconcilliation
    image: fluxcd/flux:1.21.2
    script: |
      flux -n ndtech-staging reconcile kustomization ndtech-staging