---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: ndtech-buildbarn
  namespace: ndtech-staging
spec:
  interval: 30s
  ref:
    branch: main
  url: https://github.com/22ndtech/ndtech-buildbarn