apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ndtech-node-api
  namespace: ndtech-staging
spec:
  interval: 5m
  chart:
    spec:
      chart: ./charts/ndtech-node-api
      version: 0.0.11
      sourceRef:
        kind: GitRepository
        name: ndtech-node-api
        namespace: ndtech
      interval: 1m
  values:
    deployment:
      replicas: 1
      namespace: ndtech-staging
      imageVersion: 0.0.3
      nodeApiUrl: ndtech-staging.www.22ndtech.com
