---
# The ndtech-staging Pipeline will run through several tasks:
# - source is pulled from git
# - source is built into an image
# - image output is pushed to dockerhub
# - cloudevent emitted
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: github
  namespace: ndtech-staging
spec:
  workspaces:
    - name: app-source
    - name: config-source
  params:
    - name: environment
      default: ndtech-staging
    - name: app-name
      default: ndtech
    - name: gitHubOrg
      default: 22ndtech
    - name: gitHubRepo
      default: ndtech
    - name: gitHubUser
      default: 22ndtech
    - name: appImage
      default: ndtech-website
    - name: buildRevision
  resources:
    - name: source-repo
      type: git
    - name: image-source
      type: image

  tasks:

    - name: clone-app-repo
      taskRef:
        name: git-clone
      workspaces:
      - name: output
        workspace: app-source
      params:
        - name: url
          value: https://github.com/$(params.gitHubOrg)/$(params.gitHubRepo).git
        
    - name: clone-config-repo
      taskRef:
        name: git-clone
      workspaces:
      - name: output
        workspace: config-source
      params:
      - name: url
        value: https://github.com/$(params.gitHubOrg)/ndtech-flux-staging.git
      - name: revision
        value: main

    - name: get-app-version
      params:
        - name: app-name
          value: "$(params.app-name)"
      taskRef:
        name: get-app-version
      runAfter:
        - clone-app-repo
      workspaces:
      - name: app-source
        workspace: app-source

    - name: build-and-push-docker-image
      taskRef:
        name: kaniko
      runAfter:
        - get-app-version
      params:
        - name: IMAGE
          value: "$(params.gitHubOrg)/$(params.gitHubRepo):$(tasks.get-app-version.results.app-version)"
        - name: BUILDER_IMAGE
          value: gcr.io/kaniko-project/executor:v1.5.0-debug
      workspaces:
      - name: source
        workspace: app-source

    - name: deploy-to-ndtech-staging
      taskRef:
        name: deploy-to-ndtech-staging
      runAfter:
        - build-and-push-docker-image
      params:
        - name: buildRevision
          value: "$(params.buildRevision)"
        - name: app-name
          value: "$(params.app-name)"
        - name: app-version
          value: "$(tasks.get-app-version.results.app-version)"
      workspaces:
        - name: config-source
          workspace: config-source