---
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: github
  namespace: ndtech-staging
spec:
  serviceAccountName: tekton-triggers-admin
  triggers:
    - bindings:
      - ref: github
      template:
        ref: github
      interceptors:
        - github:
            secretRef:
              secretName: github-secret
              secretKey: secretToken
            eventTypes:
              - push
  resources:
    kubernetesResource:
      serviceType: ClusterIP
      spec:
        template:
          metadata:
            labels:
              app: tekton-triggers-listener
          spec:
            serviceAccountName: tekton-triggers-admin
            containers:
              - resources:
                  requests:
                    memory: "64Mi"
                    cpu: "250m"
                  limits:
                    memory: "128Mi"
                    cpu: "500m"