---
# The ndtech-staging Pipeline will run through several tasks:
# - source is pulled from git
# - source is built into an image
# - image output is pushed to dockerhub
# - cloudevent emitted
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: github
  namespace: ndtech-staging
spec:
  workspaces:
    - name: app-source
    - name: config-source
  params:
    - name: environment
      default: ndtech-staging
    - name: app-name
      default: ndtech
    - name: gitHubOrg
      default: 22ndtech
    - name: gitHubRepo
      default: ndtech
    - name: gitHubUser
      default: 22ndtech
    - name: appImage
      default: ndtech-website
    - name: buildRevision
  resources:
    - name: source-repo
      type: git
    - name: image-source
      type: image
  tasks:
    - name: deploy-to-ndtech-staging
      taskRef:
        name: deploy-to-ndtech-staging
      params:
        - name: environment
          value: "$(params.environment)"
        - name: app-name
          value: "$(params.app-name)"
        - name: gitHubOrg
          value: "$(params.gitHubOrg)"
        - name: gitHubRepo
          value: "$(params.gitHubRepo)"
        - name: gitHubUser
          value: "$(params.gitHubUser)"
        - name: appImage
          value: "$(params.appImage)"
        - name: buildRevision
          value: "$(params.buildRevision)"
      resources:
        inputs:
          - name: image-source
            resource: image-source
      workspaces:
        - name: app-source
          workspace: app-source
        - name: config-source
          workspace: config-source