
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ndtech-staging.22ndtech-ca-staging
  namespace: ndtech-staging
spec:
  secretName: letsencrypt-staging-22ndtech
  dnsNames:
  - ndtech-staging.22ndtech.com
  - ndtech-staging.www.22ndtech.com
  - ndtech-staging.api.22ndtech.com
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
    group: cert-manager.io
  isCA: true
  commonName: ndtech-staging.22ndtech.com