
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: 22ndtech-ca
  namespace: ndtech-staging
spec:
  secretName: letsencrypt-22ndtech
  dnsNames:
  - ndtech-staging.22ndtech.com
  - ndtech-staging.www.22ndtech.com
  - ndtech-staging.api.22ndtech.com
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
    group: cert-manager.io
  isCA: true
  commonName: ndtech-staging.22ndtech.com