---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: jaackd-reality-ca-staging
  namespace: ndtech-staging
spec:
  secretName: letsencrypt-staging
  dnsNames:
  - ndtech-staging.jaackdreality.com
  - ndtech-staging.www.jaackdreality.com
  - ndtech-staging.tekton.jaackdreality.com
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
    group: cert-manager.io
  isCA: true
  commonName: ndtech-staging.jaackdreality.com