---
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: tekton-triggers-listener
  namespace: ndtech-staging
spec:
  serviceAccountName: tekton-triggers-admin
  triggers:
    - bindings:
      - ref: tekton-triggers-pipelinebinding
      template:
        ref: tekton-triggers-triggertemplate
  resources:
    kubernetesResource:
      serviceType: LoadBalancer
      spec:
        template:
          metadata:
            labels:
              app: tekton-triggers-listener
          spec:
            serviceAccountName: tekton-triggers-admin
            containers:
              - resources:
                  requests:
                    memory: "64Mi"
                    cpu: "250m"
                  limits:
                    memory: "128Mi"
                    cpu: "500m"