---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ndtech-sapper
  namespace: ndtech
spec:
  interval: 5m
  chart:
    spec:
      chart: ./deploy/ndtech-sapper
      version: 0.0.1.7
      sourceRef:
        kind: GitRepository
        name: ndtech-sapper
        namespace: flux-system
      interval: 1m
  values:
    deployment:
      replicas: 1
      namespace: ndtech
      imageVersion: 0.0.3
---
apiVersion: v1
kind: Service
metadata:
  name: ndtech-sapper
  namespace: ndtech
  annotations:
    external-dns.alpha.kubernetes.io/hostname: www.jaackdreality.com
spec:
  selector:
    app: ndtech-sapper
  type: NodePort
  ports:
    - protocol: TCP
      port: 3000
      nodePort: 30080