---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ndtech-sapper
  namespace: ndtech
spec:
  interval: 5m
  chart:
    spec:
      chart: ./deploy/ndtech-sapper
      version: 0.0.2
      sourceRef:
        kind: GitRepository
        name: ndtech-sapper
        namespace: ndtech
      interval: 1m
  values:
    deployment:
      replicas: 1
      namespace: ndtech
      imageVersion: 0.0.4
---
apiVersion: v1
kind: Service
metadata:
  name: ndtech-sapper
  namespace: ndtech
  annotations:
    external-dns.alpha.kubernetes.io/hostname: jaackdreality.com, www.jaackdreality.com, tekton.jaackdreality.com
spec:
  selector:
    app: ndtech-sapper
  ports:
    - port: 80
      targetPort: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jaackdreality-com
  namespace: ndtech
  annotations:
    external-dns.alpha.kubernetes.io/hostname: jaackdreality.com, www.jaackdreality.com, tekton.jaackdreality.com
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  tls:
    - secretName: letsencrypt
      hosts:
        - jaackdreality.com
        - www.jaackdreality.com
        - tekton.jaackdreality.com
  rules:
    - host: jaackdreality.com
      http:
        paths:
          - backend:
             service:
              name: ndtech-sapper
              port:
                number: 80
            path: /
            pathType: ImplementationSpecific
    - host: www.jaackdreality.com
      http:
        paths:
          - backend:
             service:
              name: ndtech-sapper
              port:
                number: 80
            path: /
            pathType: ImplementationSpecific
    - host: tekton.jaackdreality.com
      http:
        paths:
          - backend:
             service:
              name: el-getting-started-listener
              port:
                number: 8080
            path: /
            pathType: ImplementationSpecific
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: jaackd-reality-ca-staging
  namespace: ndtech
spec:
  secretName: letsencrypt-staging
  dnsNames:
  - jaackdreality.com
  - www.jaackdreality.com
  - tekton.jaackdreality.com
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
    group: cert-manager.io
  isCA: true
  commonName: jaackdreality.com
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: jaackd-reality-ca
  namespace: ndtech
spec:
  secretName: letsencrypt
  dnsNames:
  - jaackdreality.com
  - www.jaackdreality.com
  - tekton.jaackdreality.com
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
    group: cert-manager.io
  isCA: true
  commonName: jaackdreality.com