---
apiVersion: mongodb.com/v1
kind: MongoDB
metadata:
  name: mongodb
  namespace: ndtech-staging
spec:
  members: 1
  type: ReplicaSet
  version: "4.2.6"
  security:
    authentication:
      modes: ["SCRAM"]
  users:
    - name: mongoadmin
      db: admin
      passwordSecretRef:
        name: mongoadmin
      roles:
        - name: clusterAdmin
          db: admin
        - name: userAdminAnyDatabase
          db: admin
    - name: ndtech-users
      db: ndtech-users
      passwordSecretRef:
        name: ndtech-users
      roles:
        - name: readWrite
          db: ndtech-users
    - name: ndtech-entities
      db: ndtech-entities
      passwordSecretRef:
        name: ndtech-entities
      roles:
        - name: readWrite
          db: ndtech-entities